### ISSUE TITLE
hi，how to download the VQA-cp v2 datasets? can you provide the linking? thank you!

### ISSUE THREAD

**Issue by double125** [guoyang9/LXMERT-VQACP#1]

**Comment by guoyang9** [comment]
The file size is a little bit large. 
Maybe you should ask the authors for the link updating.

**Comment by alice-cool** [comment]
Dear scholar,
So the download link?

**Comment by alice-cool** [comment]
https://computing.ece.vt.edu/~aish/vqacp/
